a=input("what is your name")
b=int(input("in which acadamic year you are in"))
c=input("which course you are in")
d=int(input("what is your date of birth"))
print("you are",a,"you are in",c,"your acadamic year is",b,"your date of birth is",d)